alias api.up="docker compose up -d"
alias api.down="docker compose down"
alias api="docker exec -it api"
alias api.logs="docker logs -f api"
alias api.bash="api bash"
alias api.composer="api composer"
alias api.php="api php"
