services:
  api:
    container_name: api
    build:
      context: ./.docker/api
    restart: always
    command: php -S 0.0.0.0:8001 -t public
    volumes:
      - .:/var/www
    ports:
      - "8001:8001"
      - "9003:9003"
